stages:
  - build

build_job:
  stage: build
  only:
    - branches
  script:
    - 'cd ConsoleApp2'
    - '"C:\Tools\nuget.exe" restore'
    - '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\amd64\MSBuild.exe" ConsoleApp2.sln'  
  artifacts:
    paths:
      - 'C:\Users\makes\source\repos\ConsoleApp2\ConsoleApp2\bin\Debug\netcoreapp3.1\ConsoleApp2.exe'
